server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false

logging:
  level:
    ROOT: debug
    org.springframework: debug
    org.springframework.security: debug
    org.springframework.data: debug
    com.snail: debug
  #file: /Users/lipan/application.log